---
- name: "Update install node versions if required"
  ansible.builtin.dnf:
    name:
      - python3.12
      - java-1.8.0-openjdk.x86_64
    state: present
  become: true
- name: Install ansible galaxy subdependencies
  ansible.builtin.shell: |
    ansible-galaxy collection install community.general
- name: "Switch python version to latest installed"
  community.general.alternatives:
    name: python3
    path: /usr/bin/python3.12
    link: /usr/bin/python3
    state: selected
- name: "Install python modules required to run playbooks"
  ansible.builtin.pip:
    name:
      - kubernetes >= 24.2.0
      - PyYAML >= 3.11
      - jsonpatch
  become: true
